name: my-workflow
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]


jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: cd ./frontend-react
      - run: bun install
      - run: bun run build
